# Generated by Django 4.2.6 on 2026-03-20 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Relay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="Relay", max_length=100, null=True
                    ),
                ),
                ("base_url", models.CharField(max_length=255)),
                ("is_visible_on_public_pages", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "relays",
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("short_name", models.SlugField(max_length=100, unique=True)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "frontend_type",
                    models.CharField(
                        choices=[
                            ("icecast", "Icecast"),
                            ("shoutcast", "Shoutcast"),
                            ("remote", "Remote"),
                            ("none", "None"),
                        ],
                        default="icecast",
                        max_length=100,
                    ),
                ),
                ("frontend_config", models.JSONField(blank=True, null=True)),
                (
                    "backend_type",
                    models.CharField(
                        choices=[("liquidsoap", "Liquidsoap"), ("none", "None")],
                        default="liquidsoap",
                        max_length=100,
                    ),
                ),
                ("backend_config", models.JSONField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.URLField(blank=True, max_length=255, null=True)),
                ("genre", models.CharField(blank=True, max_length=255, null=True)),
                ("radio_base_dir", models.CharField(max_length=255)),
                ("enable_requests", models.BooleanField(default=False)),
                (
                    "request_delay",
                    models.IntegerField(blank=True, default=5, null=True),
                ),
                (
                    "request_threshold",
                    models.IntegerField(blank=True, default=15, null=True),
                ),
                (
                    "disconnect_deactivate_streamer",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("enable_streamers", models.BooleanField(default=False)),
                ("is_streamer_live", models.BooleanField(default=False)),
                ("enable_public_page", models.BooleanField(default=True)),
                ("enable_public_api", models.BooleanField(default=True)),
                ("enable_on_demand", models.BooleanField(default=False)),
                ("enable_on_demand_download", models.BooleanField(default=True)),
                ("enable_hls", models.BooleanField(default=False)),
                ("api_history_items", models.SmallIntegerField(default=5)),
                ("timezone", models.CharField(default="UTC", max_length=100)),
                ("max_bitrate", models.SmallIntegerField(default=0)),
                ("max_mounts", models.SmallIntegerField(default=0)),
                ("max_hls_streams", models.SmallIntegerField(default=0)),
                ("branding_config", models.JSONField(blank=True, null=True)),
                (
                    "adapter_api_key",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "fallback_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("needs_restart", models.BooleanField(default=False)),
                ("has_started", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "backups_storage_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stations_backups",
                        to="media.storagelocation",
                    ),
                ),
                (
                    "media_storage_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stations_media",
                        to="media.storagelocation",
                    ),
                ),
                (
                    "podcasts_storage_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stations_podcasts",
                        to="media.storagelocation",
                    ),
                ),
                (
                    "recordings_storage_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stations_recordings",
                        to="media.storagelocation",
                    ),
                ),
            ],
            options={
                "db_table": "station",
            },
        ),
        migrations.CreateModel(
            name="StationPlaylist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("default", "Standard"),
                            ("once_per_x_songs", "Once per x songs"),
                            ("once_per_x_minutes", "Once per x minutes"),
                            ("once_per_day", "Once per day"),
                            ("custom", "Custom"),
                            ("none", "None"),
                        ],
                        default="default",
                        max_length=50,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("songs", "Songs"), ("remote_url", "Remote URL")],
                        default="songs",
                        max_length=50,
                    ),
                ),
                (
                    "playback_order",
                    models.CharField(
                        choices=[
                            ("shuffle", "Shuffle"),
                            ("random", "Random"),
                            ("sequential", "Sequential"),
                        ],
                        default="shuffle",
                        max_length=50,
                    ),
                ),
                ("remote_url", models.CharField(blank=True, max_length=255, null=True)),
                ("remote_type", models.CharField(blank=True, max_length=25, null=True)),
                ("remote_buffer", models.SmallIntegerField(default=0)),
                ("is_enabled", models.BooleanField(default=True)),
                ("is_jingle", models.BooleanField(default=False)),
                ("avoid_duplicates", models.BooleanField(default=True)),
                ("include_in_requests", models.BooleanField(default=True)),
                ("include_in_on_demand", models.BooleanField(default=False)),
                ("play_per_songs", models.SmallIntegerField(default=0)),
                ("play_per_minutes", models.SmallIntegerField(default=0)),
                ("play_per_hour_minute", models.SmallIntegerField(default=0)),
                ("weight", models.SmallIntegerField(default=3)),
                ("played_at", models.DateTimeField(blank=True, null=True)),
                ("queue_reset_at", models.DateTimeField(blank=True, null=True)),
                (
                    "backend_options",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("queue", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlists",
                        to="stations.station",
                    ),
                ),
            ],
            options={
                "db_table": "station_playlists",
            },
        ),
        migrations.CreateModel(
            name="StationStreamer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("streamer_username", models.CharField(max_length=50)),
                ("streamer_password", models.CharField(max_length=255)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("enforce_schedule", models.BooleanField(default=False)),
                ("reactivate_at", models.IntegerField(blank=True, null=True)),
                ("art_updated_at", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streamers",
                        to="stations.station",
                    ),
                ),
            ],
            options={
                "db_table": "station_streamers",
                "unique_together": {("station", "streamer_username")},
            },
        ),
        migrations.CreateModel(
            name="StationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.SmallIntegerField(default=0)),
                ("end_time", models.SmallIntegerField(default=0)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("days", models.CharField(blank=True, max_length=50, null=True)),
                ("loop_once", models.BooleanField(default=False)),
                (
                    "playlist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_items",
                        to="stations.stationplaylist",
                    ),
                ),
                (
                    "streamer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_items",
                        to="stations.stationstreamer",
                    ),
                ),
            ],
            options={
                "db_table": "station_schedules",
            },
        ),
        migrations.CreateModel(
            name="StationRemote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("is_visible_on_public_pages", models.BooleanField(default=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("icecast", "Icecast"),
                            ("shoutcast1", "Shoutcast v1"),
                            ("shoutcast2", "Shoutcast v2"),
                        ],
                        max_length=50,
                    ),
                ),
                ("enable_autodj", models.BooleanField(default=False)),
                (
                    "autodj_format",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("autodj_bitrate", models.SmallIntegerField(blank=True, null=True)),
                (
                    "custom_listen_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("url", models.CharField(max_length=255)),
                ("mount", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "admin_password",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("source_port", models.SmallIntegerField(blank=True, null=True)),
                (
                    "source_mount",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "source_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "source_password",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("listeners_unique", models.IntegerField(default=0)),
                ("listeners_total", models.IntegerField(default=0)),
                (
                    "relay",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remotes",
                        to="stations.relay",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remotes",
                        to="stations.station",
                    ),
                ),
            ],
            options={
                "db_table": "station_remotes",
            },
        ),
        migrations.CreateModel(
            name="StationPlaylistFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=500)),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to="stations.stationplaylist",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlist_folders",
                        to="stations.station",
                    ),
                ),
            ],
            options={
                "db_table": "station_playlist_folders",
            },
        ),
        migrations.CreateModel(
            name="StationMount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=255)),
                ("is_visible_on_public_pages", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "fallback_mount",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("relay_url", models.CharField(blank=True, max_length=255, null=True)),
                ("authhash", models.CharField(blank=True, max_length=255, null=True)),
                ("max_listener_duration", models.IntegerField(default=0)),
                ("enable_autodj", models.BooleanField(default=True)),
                (
                    "autodj_format",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("autodj_bitrate", models.SmallIntegerField(blank=True, null=True)),
                (
                    "custom_listen_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("intro_path", models.CharField(blank=True, max_length=255, null=True)),
                ("frontend_config", models.TextField(blank=True, null=True)),
                ("listeners_unique", models.IntegerField(default=0)),
                ("listeners_total", models.IntegerField(default=0)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mounts",
                        to="stations.station",
                    ),
                ),
            ],
            options={
                "db_table": "station_mounts",
            },
        ),
        migrations.CreateModel(
            name="StationHlsStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("aac", "AAC (Low Complexity)"),
                            ("aac_he_v1", "HE-AAC v1"),
                            ("aac_he_v2", "HE-AAC v2"),
                        ],
                        default="aac",
                        max_length=20,
                    ),
                ),
                ("bitrate", models.SmallIntegerField(default=128)),
                ("listeners", models.IntegerField(default=0)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hls_streams",
                        to="stations.station",
                    ),
                ),
            ],
            options={
                "db_table": "station_hls_streams",
            },
        ),
        migrations.CreateModel(
            name="SftpUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("public_keys", models.TextField(blank=True, null=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sftp_users",
                        to="stations.station",
                    ),
                ),
            ],
            options={
                "db_table": "sftp_user",
            },
        ),
    ]
