# Generated by Django 5.2.12 on 2026-03-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='ad_config',
            field=models.JSONField(blank=True, default=dict, help_text='Ad injection settings (intervals, providers).'),
        ),
        migrations.AddField(
            model_name='station',
            name='cdn_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='hls_cdn_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='branding_config',
            field=models.JSONField(blank=True, default=dict, help_text='Custom branding like colors, logos, and social widgets.'),
        ),
    ]
