# Generated by Django 5.2.12 on 2026-03-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_station_ad_config_station_cdn_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='radio_base_dir',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
