# Generated by Django 5.2.12 on 2026-03-24 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_alter_station_radio_base_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationschedule',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='stations.station'),
        ),
        migrations.AlterField(
            model_name='stationhlsstream',
            name='format',
            field=models.CharField(choices=[('mp3', 'MP3'), ('aac', 'AAC (Low Complexity)'), ('aac_he_v1', 'HE-AAC v1'), ('aac_he_v2', 'HE-AAC v2')], default='aac', max_length=20),
        ),
        migrations.CreateModel(
            name='StationAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='ads/')),
                ('media_path', models.CharField(blank=True, max_length=500, null=True)),
                ('media_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('play_interval', models.SmallIntegerField(default=0, help_text='Play every X minutes (0 to disable)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='stations.station')),
            ],
            options={
                'db_table': 'station_advertisements',
            },
        ),
        migrations.AddField(
            model_name='stationschedule',
            name='advertisement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='stations.stationadvertisement'),
        ),
    ]
