# Generated by Django 5.2.12 on 2026-03-25 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_station_guardian_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='country',
            field=models.CharField(blank=True, default='Cameroun', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='station',
            name='language',
            field=models.CharField(blank=True, default='fr', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='station_logos/'),
        ),
        migrations.AddField(
            model_name='station',
            name='logo_external_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='stream_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='stationplaylist',
            name='type',
            field=models.CharField(choices=[('default', 'Standard'), ('once_per_hour', 'Once per hour'), ('once_per_x_songs', 'Once per x songs'), ('once_per_x_minutes', 'Once per x minutes'), ('once_per_day', 'Once per day'), ('custom', 'Custom'), ('none', 'None')], default='default', max_length=50),
        ),
    ]
