# Generated by Django 5.2.12 on 2026-03-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_station_country_station_creator_station_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationadvertisement',
            name='last_played_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
