# Generated by Django 5.2.12 on 2026-03-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0008_stationadvertisement_last_played_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationadvertisement',
            name='target_cities',
            field=models.CharField(blank=True, help_text='Comma-separated city names', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='stationadvertisement',
            name='target_countries',
            field=models.CharField(blank=True, help_text='Comma-separated ISO country codes (ex: CM,FR)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stationadvertisement',
            name='target_plays',
            field=models.IntegerField(default=0, help_text='Total plays objective for the campaign'),
        ),
    ]
