# Generated by Django 5.2.12 on 2026-03-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_stationadvertisement_target_cities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationadvertisement',
            name='target_listeners',
            field=models.IntegerField(default=0, help_text='Total unique listeners objective for the campaign'),
        ),
    ]
