# Generated by Django 5.2.12 on 2026-03-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0010_stationadvertisement_target_listeners'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='plan',
            field=models.CharField(choices=[('free', 'Gratuit'), ('pro', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='free', max_length=50),
        ),
    ]
