# Generated by Django 5.2.12 on 2026-04-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0011_station_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'permissions': [('manage_station', 'Peut tout gérer sur la station'), ('manage_station_profile', 'Peut gérer le profil de la station'), ('manage_station_media', 'Peut gérer les médias'), ('manage_station_playlists', 'Peut gérer les playlists'), ('manage_station_streamers', 'Peut gérer les streamers'), ('manage_station_mounts', 'Peut gérer les points de montage'), ('manage_station_remotes', 'Peut gérer les remotes'), ('manage_station_webhooks', 'Peut gérer les webhooks'), ('manage_station_podcasts', 'Peut gérer les podcasts'), ('manage_station_hls', 'Peut gérer le HLS'), ('manage_station_analytics', 'Peut voir les statistiques')]},
        ),
    ]
