# Generated by Django 5.2.12 on 2026-04-03 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('stations', '0012_alter_station_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='billing.subscription'),
        ),
    ]
