# Generated by Django 5.2.12 on 2026-04-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0013_station_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('play_interval', models.SmallIntegerField(default=15, help_text='Inject every X minutes in all target stations')),
                ('advertiser_name', models.CharField(blank=True, max_length=255)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stations', models.ManyToManyField(related_name='global_campaigns', to='stations.station')),
            ],
            options={
                'db_table': 'global_campaigns',
            },
        ),
    ]
