# Generated by Django 5.2.12 on 2026-04-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0014_globalcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='max_storage_gb',
            field=models.IntegerField(default=5, help_text='Station specific storage quota in GB'),
        ),
    ]
