# Generated by Django 4.2.6 on 2026-03-20 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stations", "0001_initial"),
        ("media", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
                ("link", models.URLField(blank=True, max_length=255, null=True)),
                ("language", models.CharField(default="en", max_length=10)),
                ("author", models.CharField(blank=True, max_length=150, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="podcast_art/"),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "podcasts",
            },
        ),
        migrations.CreateModel(
            name="PodcastCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "podcast categories",
                "db_table": "podcast_categories",
            },
        ),
        migrations.CreateModel(
            name="PodcastEpisode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                ("link", models.URLField(blank=True, max_length=255, null=True)),
                ("publish_at", models.DateTimeField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=True)),
                ("explicit", models.BooleanField(default=False)),
                ("season", models.IntegerField(blank=True, null=True)),
                ("episode", models.IntegerField(blank=True, null=True)),
                (
                    "episode_type",
                    models.CharField(
                        choices=[
                            ("full", "Full"),
                            ("trailer", "Trailer"),
                            ("bonus", "Bonus"),
                        ],
                        default="full",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "podcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="podcasts.podcast",
                    ),
                ),
            ],
            options={
                "db_table": "podcast_episodes",
            },
        ),
        migrations.CreateModel(
            name="PodcastMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("length", models.FloatField(default=0)),
                ("length_text", models.CharField(blank=True, max_length=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "episode",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="podcasts.podcastepisode",
                    ),
                ),
                (
                    "storage_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="media.storagelocation",
                    ),
                ),
            ],
            options={
                "db_table": "podcast_media",
            },
        ),
        migrations.AddField(
            model_name="podcast",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="podcasts", to="podcasts.podcastcategory"
            ),
        ),
        migrations.AddField(
            model_name="podcast",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="podcasts",
                to="stations.station",
            ),
        ),
        migrations.AddField(
            model_name="podcast",
            name="storage_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="media.storagelocation",
            ),
        ),
    ]
