# Generated by Django 4.2.6 on 2026-03-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("hourly", "Hourly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=15,
                    ),
                ),
                ("moment", models.DateTimeField()),
                ("number_min", models.IntegerField(default=0)),
                ("number_max", models.IntegerField(default=0)),
                (
                    "number_avg",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("number_unique", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "analytics",
            },
        ),
        migrations.CreateModel(
            name="Listener",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("listener_uid", models.IntegerField()),
                ("listener_ip", models.GenericIPAddressField()),
                ("listener_user_agent", models.CharField(max_length=255)),
                ("listener_hash", models.CharField(max_length=32)),
                ("timestamp_start", models.DateTimeField()),
                ("timestamp_end", models.DateTimeField(blank=True, null=True)),
                ("device_is_mobile", models.BooleanField(default=False)),
                ("device_is_bot", models.BooleanField(default=False)),
                (
                    "device_browser_family",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "device_os_family",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "location_country",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "location_region",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "location_city",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("location_lat", models.FloatField(blank=True, null=True)),
                ("location_lon", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "listener",
            },
        ),
    ]
