# Generated by Django 4.2.6 on 2026-03-20 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stations", "0001_initial"),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listener",
            name="hls_stream",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stations.stationhlsstream",
            ),
        ),
        migrations.AddField(
            model_name="listener",
            name="mount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stations.stationmount",
            ),
        ),
        migrations.AddField(
            model_name="listener",
            name="remote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stations.stationremote",
            ),
        ),
        migrations.AddField(
            model_name="listener",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listener_history",
                to="stations.station",
            ),
        ),
        migrations.AddField(
            model_name="analytics",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to="stations.station",
            ),
        ),
        migrations.AddIndex(
            model_name="listener",
            index=models.Index(
                fields=["timestamp_end", "timestamp_start"],
                name="listener_timesta_89d69d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="listener",
            index=models.Index(
                fields=["location_country"], name="listener_locatio_8fc91d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listener",
            index=models.Index(
                fields=["device_os_family"], name="listener_device__c878bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listener",
            index=models.Index(
                fields=["device_browser_family"], name="listener_device__0810fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analytics",
            index=models.Index(
                fields=["type", "moment"], name="analytics_type_626d15_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="analytics",
            unique_together={("station", "type", "moment")},
        ),
    ]
