# Generated by Django 5.2.12 on 2026-03-30 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
        ('stations', '0008_stationadvertisement_last_played_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementPlayback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_start', models.DateTimeField(auto_now_add=True)),
                ('timestamp_end', models.DateTimeField(blank=True, null=True)),
                ('listeners_start', models.IntegerField(default=0)),
                ('listeners_end', models.IntegerField(default=0)),
                ('is_confirmed_by_log', models.BooleanField(default=False)),
                ('log_line', models.TextField(blank=True, null=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_history', to='stations.stationadvertisement')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_playback_history', to='stations.station')),
            ],
            options={
                'db_table': 'advertisement_playback',
                'indexes': [models.Index(fields=['timestamp_start'], name='advertiseme_timesta_6f5429_idx'), models.Index(fields=['station', 'advertisement'], name='advertiseme_station_c6916b_idx')],
            },
        ),
    ]
