# Generated by Django 4.2.6 on 2026-03-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_unique_identifier",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("base_url", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "instance_name",
                    models.CharField(default="AzuraCast", max_length=255),
                ),
                ("prefer_browser_url", models.BooleanField(default=True)),
                ("use_radio_proxy", models.BooleanField(default=True)),
                ("always_use_ssl", models.BooleanField(default=False)),
                (
                    "api_access_control",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("public_theme", models.CharField(default="light", max_length=25)),
                ("hide_album_art", models.BooleanField(default=False)),
                (
                    "homepage_redirect_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "default_album_art_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("hide_product_name", models.BooleanField(default=False)),
                ("public_custom_css", models.TextField(blank=True, null=True)),
                ("public_custom_js", models.TextField(blank=True, null=True)),
                ("internal_custom_css", models.TextField(blank=True, null=True)),
                ("history_keep_days", models.IntegerField(default=14)),
                ("enable_liquidsoap_editing", models.BooleanField(default=True)),
                ("enable_static_nowplaying", models.BooleanField(default=False)),
                ("analytics", models.CharField(default="all", max_length=50)),
                ("check_for_updates", models.BooleanField(default=True)),
                ("update_results", models.JSONField(blank=True, null=True)),
                ("update_last_run", models.IntegerField(default=0)),
                ("setup_complete_time", models.IntegerField(default=0)),
                ("sync_disabled", models.BooleanField(default=False)),
                ("sync_last_run", models.IntegerField(default=0)),
                ("external_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "use_external_album_art_when_processing_media",
                    models.BooleanField(default=False),
                ),
                ("use_external_album_art_in_apis", models.BooleanField(default=False)),
                (
                    "last_fm_api_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "geolite_license_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("geolite_last_run", models.IntegerField(default=0)),
                ("backup_enabled", models.BooleanField(default=False)),
                (
                    "backup_time_code",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("backup_exclude_media", models.BooleanField(default=False)),
                ("backup_keep_copies", models.SmallIntegerField(default=0)),
                ("backup_storage_location", models.IntegerField(blank=True, null=True)),
                ("backup_format", models.CharField(default="zip", max_length=25)),
                ("backup_last_run", models.IntegerField(default=0)),
                ("backup_last_output", models.TextField(blank=True, null=True)),
                ("mail_enabled", models.BooleanField(default=False)),
                (
                    "mail_sender_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "mail_sender_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "mail_smtp_host",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("mail_smtp_port", models.IntegerField(default=587)),
                ("mail_smtp_secure", models.CharField(default="tls", max_length=25)),
                ("mail_smtp_auth", models.BooleanField(default=False)),
                (
                    "mail_smtp_user",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mail_smtp_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "settings",
                "db_table": "settings",
            },
        ),
    ]
