# Generated by Django 4.2.6 on 2026-03-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StationQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=150, null=True)),
                ("artist", models.CharField(blank=True, max_length=150, null=True)),
                ("album", models.CharField(blank=True, max_length=150, null=True)),
                ("sent_to_autodj", models.BooleanField(default=False)),
                ("is_played", models.BooleanField(default=False)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "autodj_custom_uri",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("timestamp_cued", models.DateTimeField(auto_now_add=True)),
                ("timestamp_played", models.DateTimeField(blank=True, null=True)),
                ("duration", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "station_queue",
            },
        ),
        migrations.CreateModel(
            name="StationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("played_at", models.DateTimeField(blank=True, null=True)),
                ("skip_delay", models.BooleanField(default=False)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "db_table": "station_requests",
            },
        ),
    ]
