# Generated by Django 4.2.6 on 2026-03-20 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stations", "0001_initial"),
        ("media", "0001_initial"),
        ("autodj", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stationrequest",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request_items",
                to="stations.station",
            ),
        ),
        migrations.AddField(
            model_name="stationrequest",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="media.stationmedia"
            ),
        ),
        migrations.AddField(
            model_name="stationqueue",
            name="media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="media.stationmedia",
            ),
        ),
        migrations.AddField(
            model_name="stationqueue",
            name="playlist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stations.stationplaylist",
            ),
        ),
        migrations.AddField(
            model_name="stationqueue",
            name="request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="autodj.stationrequest",
            ),
        ),
        migrations.AddField(
            model_name="stationqueue",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queue_items",
                to="stations.station",
            ),
        ),
    ]
