# Generated by Django 5.2.12 on 2026-03-30 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodj', '0002_initial'),
        ('stations', '0008_stationadvertisement_last_played_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationqueue',
            name='advertisement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.stationadvertisement'),
        ),
    ]
