import os
from typing import List
from urllib.parse import quote

from django.conf import settings

class LiquidsoapConfigWriter:
    def __init__(self, station):
        self.station = station
        self.lines = []

    def append_line(self, line: str):
        self.lines.append(line)

    def append_block(self, block: str):
        self.lines.append(block)

    def generate_config(self) -> str:
        self.write_header()
        self.write_custom_section('custom_top')
        self.write_custom_section('custom_pre_playlists')
        self.write_playlists()
        self.write_crossfade()
        self.write_custom_section('custom_pre_live')
        self.write_harbor()
        self.write_custom_section('custom_pre_broadcast')
        self.write_processing()
        self.write_outputs()
        if getattr(self.station, 'enable_hls', False):
            self.write_hls()
        self.write_custom_section('custom_post_broadcast')
        self.write_custom_section('custom_bottom')
        return "\n".join(self.lines)

    def write_custom_section(self, section_name: str):
        backend_config = self.station.backend_config or {}
        custom_config = backend_config.get(section_name, "")
        if custom_config:
            self.append_block(f"# Custom Configuration: {section_name}\n{custom_config}")

    def write_header(self):
        config_dir = os.path.join(self.station.radio_base_dir, 'config')
        pidfile = os.path.join(config_dir, 'liquidsoap.pid')
        logfile = os.path.join(config_dir, 'liquidsoap.log')
        
        # Ports and API settings
        backend_config = self.station.backend_config or {}
        http_api_port = backend_config.get('telnet_port', 8000 + ((self.station.id - 1) * 10) + 5)
        
        log_level = 3 if settings.DEBUG else 2
        
        common_lib_path = getattr(settings, 'LIQUIDSOAP_LIB_PATH', '/usr/local/share/liquidsoap/azuracast.liq')
        
        fallback_path = self.station.fallback_path or "/usr/local/share/icecast/web/error.mp3"
        temp_path = os.path.join(self.station.radio_base_dir, 'temp')

        self.append_block(f"""
# WARNING! This file is automatically generated by AzuraCast Migration.
# Do not update it directly!

%include "{common_lib_path}"

log.level := {log_level}
log.file.path := "{logfile}"
init.daemon.pidfile.path := "{pidfile}"

settings.init.compact_before_start := true

environment.set("TZ", "{getattr(self.station, 'timezone', 'UTC')}")

settings.azuracast.liquidsoap_api_port := {http_api_port}
settings.azuracast.api_url := "http://backend:8000/api/internal/{self.station.id}/liquidsoap"
settings.azuracast.api_key := "{getattr(self.station, 'adapter_api_key', '')}"
settings.azuracast.fallback_path := "{fallback_path}"
settings.azuracast.temp_path := "{temp_path}"

# Performance optimizations
runtime.gc.set(runtime.gc.get().{{
  space_overhead = 80,
  allocation_policy = 2
}})

# Start HTTP API Server
azuracast.start_http_api()
""")

    def write_playlists(self):
        internal_token = quote(str(getattr(settings, 'INTERNAL_DJ_AUTH_TOKEN', '') or ''), safe='')
        self.append_block(f"""
# Playlists Configuration
def get_next_song() =
    # Call the Django API to get the next song
    # Use station_id in the URL
    response = http.get("http://backend:8000/api/autodj/nextsong/{self.station.id}/")
    # Parse the JSON response
    data = json.parse(response)
    uri = data["autodj_custom_uri"] or data["media"]["path"]
    
    # Metadata and annotations (crossfade, etc.)
    metadata = [
        ("title", data["song"]["title"]),
        ("artist", data["song"]["artist"]),
        ("album", data["song"]["album"]),
        ("song_id", string_of(data["song"]["id"])),
        ("duration", string_of(data["duration"]))
    ]
    
    # Ad-specific metadata
    if data["advertisement"] != null then
        metadata = list.add(("ad_id", string_of(data["advertisement"])), metadata)
    end
    
    # Add optional cue points and amplify if they exist
    if data["liq_amplify"] != null then
        metadata = list.add(("liq_amplify", string_of(data["liq_amplify"])), metadata)
    end
    if data["liq_cue_in"] != null then
        metadata = list.add(("liq_cue_in", string_of(data["liq_cue_in"])), metadata)
    end
    if data["liq_cue_out"] != null then
        metadata = list.add(("liq_cue_out", string_of(data["liq_cue_out"])), metadata)
    end
    if data["liq_fade_in"] != null then
        metadata = list.add(("liq_fade_in", string_of(data["liq_fade_in"])), metadata)
    end
    if data["liq_fade_out"] != null then
        metadata = list.add(("liq_fade_out", string_of(data["liq_fade_out"])), metadata)
    end
    
    request.create(uri, metadata=metadata)
end

radio = request.dynamic(id="azuracast_next_song", get_next_song)

# Ad Playback Tracking
def on_ad_event(m, event) =
    ad_id = m["ad_id"]
    if ad_id != "" then
        ignore(http.post("http://backend:8000/api/internal/playback?internal_token={internal_token}", 
            headers=[("Content-Type", "application/json")],
            data=json.stringify({{
                "station_id": {self.station.id},
                "event": event,
                "ad_id": int_of_string(ad_id)
            }})))
    end
end

radio.on_track(fun(m) -> on_ad_event(m, "start"))
radio.on_stop(fun(m) -> on_ad_event(m, "end"))
""")

    def write_crossfade(self):
        backend_config = self.station.backend_config or {}
        crossfade = backend_config.get('crossfade', 2.0)
        self.append_block(f"""
# Crossfade Configuration
settings.azuracast.default_fade := {float(crossfade)}
settings.azuracast.default_cross := {float(crossfade)}

radio = azuracast.apply_amplify(radio)
radio = azuracast.apply_crossfade(radio)
""")

    def write_harbor(self):
        backend_config = self.station.backend_config or {}
        harbor_port = backend_config.get('harbor_port', 8000 + ((self.station.id - 1) * 10) + 5)
        internal_token = quote(str(getattr(settings, 'INTERNAL_DJ_AUTH_TOKEN', '') or ''), safe='')
        
        fallback_path = self.station.fallback_path or "/usr/local/share/icecast/web/error.mp3"
        
        recording_dir = os.path.join(self.station.radio_base_dir, 'recordings')
        
        self.append_block(f"""
def dj_auth(user, password) =
    # Call the Django API for DJ authentication
    response = http.get("http://backend:8000/api/internal/auth?user=" ^ user ^ "&pass=" ^ password ^ "&station_id={self.station.id}&internal_token={internal_token}")
    data = json.parse(response)
    data["allow"] or false
end

# Harbor (Live DJ) Configuration
input_streamer = input.harbor("/", port={harbor_port}, auth=dj_auth)

# Auto-Ducking Logic
# When the DJ speaks, the music volume drops to 20%
# We use smooth_add to mix the DJ with the Radio
def mix_with_ducking(dj, music) =
  # Detect silence/sound on the DJ input
  # If DJ is active, music is lowered
  smooth_add(delay=0.5, p=0.2, normal=music, special=dj)
end

# Hierarchical Fallback: Live > Playlist > Safe File
# 1. Live DJ (with auto-ducking if needed, but here we use simple fallback for priority)
# 2. Radio (AutoDJ)
# 3. Safe File (Jingle)
safe_file = single("{fallback_path}")

# We wrap the DJ input with the music in a ducking mix
# But we only do this when the DJ is actually connected
radio = fallback(track_sensitive=false, [
  mix_with_ducking(input_streamer, radio),
  radio,
  safe_file
])

# Auto-Recording of Live Sessions
# Every time a DJ connects, we record the stream
def start_recording(m) =
    # Create directory if it doesn't exist
    system("mkdir -p {recording_dir}")
    # Filename with timestamp
    timestamp = list.assoc("start_time", m)
    filename = "{recording_dir}/live_#{{timestamp}}.mp3"
    log("Starting recording to #{{filename}}")
end

# Record the input_streamer source when it's active
output.file(%mp3(bitrate=192), 
            fallible=true,
            on_start=start_recording,
            "{recording_dir}/live_%Y%m%d_%H%M%S.mp3", 
            input_streamer)
""")

    def write_processing(self):
        backend_config = self.station.backend_config or {}
        
        # ReplayGain / Amplify
        self.append_block("""
# Audio Processing
radio = azuracast.apply_amplify(radio)
""")

        # StereoTool
        if backend_config.get('enable_stereotool', False):
            st_path = backend_config.get('stereotool_path', '/usr/local/bin/stereo_tool')
            st_config = backend_config.get('stereotool_config', '/etc/stereotool/config.sts')
            st_license = backend_config.get('stereotool_license', '')
            
            license_arg = f' -k "{st_license}"' if st_license else ""
            
            self.append_block(f"""
# StereoTool
def apply_stereotool(s) =
  pipe(process="{st_path} - - -s {st_config}{license_arg}", s)
end
radio = apply_stereotool(radio)
""")

    def write_outputs(self):
        self.append_line("# Outputs Configuration")
        for mount in self.station.mounts.filter(is_enabled=True):
            frontend_config = self.station.frontend_config or {}
            port = frontend_config.get('port', 8000 + ((self.station.id - 1) * 10))
            password = frontend_config.get('source_pw', 'password')
            
            format_str = f"%mp3(bitrate={mount.autodj_bitrate or 128})"
            if mount.autodj_format == 'aac':
                format_str = f"%fdkaac(bitrate={mount.autodj_bitrate or 128})"
            
            self.append_block(f"""
output.icecast({format_str}, 
    host="localhost", port={port}, password="{password}", 
    mount="{mount.name}", radio)
""")

    def write_hls(self):
        hls_dir = os.path.join(self.station.radio_base_dir, 'hls')
        self.append_block(f"""
# Adaptive HLS Configuration (AAC+ Multi-bitrate)
output.file.hls(
    playlist="live.m3u8",
    segment_duration=2.0, # 2s segments for low latency
    segments=5,
    segments_overhead=3,
    "{hls_dir}",
    [
        ("low", %fdkaac(bitrate=32, sbr=true)),
        ("mid", %fdkaac(bitrate=64, sbr=true)),
        ("high", %fdkaac(bitrate=128))
    ],
    radio
)
""")
