# Generated by Django 4.2.6 on 2026-03-20 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StationWebhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("generic", "Generic Webhook"),
                            ("discord", "Discord"),
                            ("telegram", "Telegram"),
                            ("email", "Email"),
                            ("tunein", "TuneIn"),
                            ("mastodon", "Mastodon"),
                            ("bluesky", "Bluesky"),
                            ("getmeradio", "GetMeRadio"),
                            ("google_analytics_v4", "Google Analytics V4"),
                            ("groupme", "GroupMe"),
                            ("matomo_analytics", "Matomo Analytics"),
                            ("radiode", "Radio.de"),
                            ("radioreg", "RadioReg"),
                        ],
                        max_length=100,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("triggers", models.JSONField(blank=True, null=True)),
                ("config", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="stations.station",
                    ),
                ),
            ],
            options={
                "db_table": "station_webhooks",
            },
        ),
    ]
