export interface Country {
  name: string;
  code: string;
  iso: string;
}

export const countries: Country[] = [
  { name: "Afghanistan", code: "+93", iso: "af" },
  { name: "Afrique du Sud", code: "+27", iso: "za" },
  { name: "Albanie", code: "+355", iso: "al" },
  { name: "Algérie", code: "+213", iso: "dz" },
  { name: "Allemagne", code: "+49", iso: "de" },
  { name: "Andorre", code: "+376", iso: "ad" },
  { name: "Angola", code: "+244", iso: "ao" },
  { name: "Anguilla", code: "+1-264", iso: "ai" },
  { name: "Antarctique", code: "+672", iso: "aq" },
  { name: "Antigua-et-Barbuda", code: "+1-268", iso: "ag" },
  { name: "Arabie Saoudite", code: "+966", iso: "sa" },
  { name: "Argentine", code: "+54", iso: "ar" },
  { name: "Arménie", code: "+374", iso: "am" },
  { name: "Aruba", code: "+297", iso: "aw" },
  { name: "Australie", code: "+61", iso: "au" },
  { name: "Autriche", code: "+43", iso: "at" },
  { name: "Azerbaïdjan", code: "+994", iso: "az" },
  { name: "Bahamas", code: "+1-242", iso: "bs" },
  { name: "Bahreïn", code: "+973", iso: "bh" },
  { name: "Bangladesh", code: "+880", iso: "bd" },
  { name: "Barbade", code: "+1-246", iso: "bb" },
  { name: "Belgique", code: "+32", iso: "be" },
  { name: "Belize", code: "+501", iso: "bz" },
  { name: "Bénin", code: "+229", iso: "bj" },
  { name: "Bermudes", code: "+1-441", iso: "bm" },
  { name: "Bhoutan", code: "+975", iso: "bt" },
  { name: "Biélorussie", code: "+375", iso: "by" },
  { name: "Bolivie", code: "+591", iso: "bo" },
  { name: "Bosnie-Herzégovine", code: "+387", iso: "ba" },
  { name: "Botswana", code: "+267", iso: "bw" },
  { name: "Brésil", code: "+55", iso: "br" },
  { name: "Brunéi", code: "+673", iso: "bn" },
  { name: "Bulgarie", code: "+359", iso: "bg" },
  { name: "Burkina Faso", code: "+226", iso: "bf" },
  { name: "Burundi", code: "+257", iso: "bi" },
  { name: "Cambodge", code: "+855", iso: "kh" },
  { name: "Cameroun", code: "+237", iso: "cm" },
  { name: "Canada", code: "+1", iso: "ca" },
  { name: "Cap-Vert", code: "+238", iso: "cv" },
  { name: "Chili", code: "+56", iso: "cl" },
  { name: "Chine", code: "+86", iso: "cn" },
  { name: "Chypre", code: "+357", iso: "cy" },
  { name: "Colombie", code: "+57", iso: "co" },
  { name: "Comores", code: "+269", iso: "km" },
  { name: "Congo-Brazzaville", code: "+242", iso: "cg" },
  { name: "Congo-Kinshasa (RDC)", code: "+243", iso: "cd" },
  { name: "Corée du Nord", code: "+850", iso: "kp" },
  { name: "Corée du Sud", code: "+82", iso: "kr" },
  { name: "Costa Rica", code: "+506", iso: "cr" },
  { name: "Côte d'Ivoire", code: "+225", iso: "ci" },
  { name: "Croatie", code: "+385", iso: "hr" },
  { name: "Cuba", code: "+53", iso: "cu" },
  { name: "Curaçao", code: "+599", iso: "cw" },
  { name: "Danemark", code: "+45", iso: "dk" },
  { name: "Djibouti", code: "+253", iso: "dj" },
  { name: "Dominique", code: "+1-767", iso: "dm" },
  { name: "Égypte", code: "+20", iso: "eg" },
  { name: "Émirats Arabes Unis", code: "+971", iso: "ae" },
  { name: "Équateur", code: "+593", iso: "ec" },
  { name: "Érythrée", code: "+291", iso: "er" },
  { name: "Espagne", code: "+34", iso: "es" },
  { name: "Estonie", code: "+372", iso: "ee" },
  { name: "Eswatini", code: "+268", iso: "sz" },
  { name: "États-Unis", code: "+1", iso: "us" },
  { name: "Éthiopie", code: "+251", iso: "et" },
  { name: "Fidji", code: "+679", iso: "fj" },
  { name: "Finlande", code: "+358", iso: "fi" },
  { name: "France", code: "+33", iso: "fr" },
  { name: "Gabon", code: "+241", iso: "ga" },
  { name: "Gambie", code: "+220", iso: "gm" },
  { name: "Géorgie", code: "+995", iso: "ge" },
  { name: "Ghana", code: "+233", iso: "gh" },
  { name: "Gibraltar", code: "+350", iso: "gi" },
  { name: "Grèce", code: "+30", iso: "gr" },
  { name: "Grenade", code: "+1-473", iso: "gd" },
  { name: "Groenland", code: "+299", iso: "gl" },
  { name: "Guadeloupe", code: "+590", iso: "gp" },
  { name: "Guam", code: "+1-671", iso: "gu" },
  { name: "Guatemala", code: "+502", iso: "gt" },
  { name: "Guernesey", code: "+44-1481", iso: "gg" },
  { name: "Guinée", code: "+224", iso: "gn" },
  { name: "Guinée Équatoriale", code: "+240", iso: "gq" },
  { name: "Guinée-Bissau", code: "+245", iso: "gw" },
  { name: "Guyana", code: "+592", iso: "gy" },
  { name: "Guyane Française", code: "+594", iso: "gf" },
  { name: "Haïti", code: "+509", iso: "ht" },
  { name: "Honduras", code: "+504", iso: "hn" },
  { name: "Hong Kong", code: "+852", iso: "hk" },
  { name: "Hongrie", code: "+36", iso: "hu" },
  { name: "Île de Man", code: "+44-1624", iso: "im" },
  { name: "Île Norfolk", code: "+672", iso: "nf" },
  { name: "Îles Caïmans", code: "+1-345", iso: "ky" },
  { name: "Îles Cook", code: "+682", iso: "ck" },
  { name: "Îles Féroé", code: "+298", iso: "fo" },
  { name: "Îles Malouines", code: "+500", iso: "fk" },
  { name: "Îles Mariannes du Nord", code: "+1-670", iso: "mp" },
  { name: "Îles Marshall", code: "+692", iso: "mh" },
  { name: "Îles Salomon", code: "+677", iso: "sb" },
  { name: "Îles Turques-et-Caïques", code: "+1-649", iso: "tc" },
  { name: "Îles Vierges Britanniques", code: "+1-284", iso: "vg" },
  { name: "Îles Vierges des États-Unis", code: "+1-340", iso: "vi" },
  { name: "Inde", code: "+91", iso: "in" },
  { name: "Indonésie", code: "+62", iso: "id" },
  { name: "Irak", code: "+964", iso: "iq" },
  { name: "Iran", code: "+98", iso: "ir" },
  { name: "Irlande", code: "+353", iso: "ie" },
  { name: "Islande", code: "+354", iso: "is" },
  { name: "Israël", code: "+972", iso: "il" },
  { name: "Italie", code: "+39", iso: "it" },
  { name: "Jamaïque", code: "+1-876", iso: "jm" },
  { name: "Japon", code: "+81", iso: "jp" },
  { name: "Jersey", code: "+44-1534", iso: "je" },
  { name: "Jordanie", code: "+962", iso: "jo" },
  { name: "Kazakhstan", code: "+7", iso: "kz" },
  { name: "Kenya", code: "+254", iso: "ke" },
  { name: "Kirghizistan", code: "+996", iso: "kg" },
  { name: "Kiribati", code: "+686", iso: "ki" },
  { name: "Koweït", code: "+965", iso: "kw" },
  { name: "Laos", code: "+856", iso: "la" },
  { name: "Lesotho", code: "+266", iso: "ls" },
  { name: "Lettonie", code: "+371", iso: "lv" },
  { name: "Liban", code: "+961", iso: "lb" },
  { name: "Libéria", code: "+231", iso: "lr" },
  { name: "Libye", code: "+218", iso: "ly" },
  { name: "Liechtenstein", code: "+423", iso: "li" },
  { name: "Lituanie", code: "+370", iso: "lt" },
  { name: "Luxembourg", code: "+352", iso: "lu" },
  { name: "Macao", code: "+853", iso: "mo" },
  { name: "Macédoine du Nord", code: "+389", iso: "mk" },
  { name: "Madagascar", code: "+261", iso: "mg" },
  { name: "Malaisie", code: "+60", iso: "my" },
  { name: "Malawi", code: "+265", iso: "mw" },
  { name: "Maldives", code: "+960", iso: "mv" },
  { name: "Mali", code: "+223", iso: "ml" },
  { name: "Malte", code: "+356", iso: "mt" },
  { name: "Maroc", code: "+212", iso: "ma" },
  { name: "Martinique", code: "+596", iso: "mq" },
  { name: "Maurice", code: "+230", iso: "mu" },
  { name: "Mauritanie", code: "+222", iso: "mr" },
  { name: "Mayotte", code: "+262", iso: "yt" },
  { name: "Mexique", code: "+52", iso: "mx" },
  { name: "Micronésie", code: "+691", iso: "fm" },
  { name: "Moldavie", code: "+373", iso: "md" },
  { name: "Monaco", code: "+377", iso: "mc" },
  { name: "Mongolie", code: "+976", iso: "mn" },
  { name: "Monténégro", code: "+382", iso: "me" },
  { name: "Montserrat", code: "+1-664", iso: "ms" },
  { name: "Mozambique", code: "+258", iso: "mz" },
  { name: "Myanmar", code: "+95", iso: "mm" },
  { name: "Namibie", code: "+264", iso: "na" },
  { name: "Nauru", code: "+674", iso: "nr" },
  { name: "Népal", code: "+977", iso: "np" },
  { name: "Nicaragua", code: "+505", iso: "ni" },
  { name: "Niger", code: "+227", iso: "ne" },
  { name: "Nigéria", code: "+234", iso: "ng" },
  { name: "Niue", code: "+683", iso: "nu" },
  { name: "Norvège", code: "+47", iso: "no" },
  { name: "Nouvelle-Calédonie", code: "+687", iso: "nc" },
  { name: "Nouvelle-Zélande", code: "+64", iso: "nz" },
  { name: "Oman", code: "+968", iso: "om" },
  { name: "Ouganda", code: "+256", iso: "ug" },
  { name: "Ouzbékistan", code: "+998", iso: "uz" },
  { name: "Pakistan", code: "+92", iso: "pk" },
  { name: "Palaos", code: "+680", iso: "pw" },
  { name: "Palestine", code: "+970", iso: "ps" },
  { name: "Panama", code: "+507", iso: "pa" },
  { name: "Papouasie-Nouvelle-Guinée", code: "+675", iso: "pg" },
  { name: "Paraguay", code: "+595", iso: "py" },
  { name: "Pays-Bas", code: "+31", iso: "nl" },
  { name: "Pérou", code: "+51", iso: "pe" },
  { name: "Philippines", code: "+63", iso: "ph" },
  { name: "Pologne", code: "+48", iso: "pl" },
  { name: "Polynésie Française", code: "+689", iso: "pf" },
  { name: "Porto Rico", code: "+1-787", iso: "pr" },
  { name: "Portugal", code: "+351", iso: "pt" },
  { name: "Qatar", code: "+974", iso: "qa" },
  { name: "Réunion", code: "+262", iso: "re" },
  { name: "Roumanie", code: "+40", iso: "ro" },
  { name: "Royaume-Uni", code: "+44", iso: "gb" },
  { name: "Russie", code: "+7", iso: "ru" },
  { name: "Rwanda", code: "+250", iso: "rw" },
  { name: "Sahara Occidental", code: "+212", iso: "eh" },
  { name: "Saint-Barthélemy", code: "+590", iso: "bl" },
  { name: "Saint-Christophe-et-Niévès", code: "+1-869", iso: "kn" },
  { name: "Saint-Marin", code: "+378", iso: "sm" },
  { name: "Saint-Martin", code: "+590", iso: "mf" },
  { name: "Saint-Pierre-et-Miquelon", code: "+508", iso: "pm" },
  { name: "Saint-Vincent-et-les-Grenadines", code: "+1-784", iso: "vc" },
  { name: "Sainte-Hélène", code: "+290", iso: "sh" },
  { name: "Sainte-Lucie", code: "+1-758", iso: "lc" },
  { name: "Salvador", code: "+503", iso: "sv" },
  { name: "Samoa", code: "+685", iso: "ws" },
  { name: "Samoa Américaines", code: "+1-684", iso: "as" },
  { name: "Sénégal", code: "+221", iso: "sn" },
  { name: "Serbie", code: "+381", iso: "rs" },
  { name: "Seychelles", code: "+248", iso: "sc" },
  { name: "Sierra Leone", code: "+232", iso: "sl" },
  { name: "Singapour", code: "+65", iso: "sg" },
  { name: "Slovaquie", code: "+421", iso: "sk" },
  { name: "Slovénie", code: "+386", iso: "si" },
  { name: "Somalie", code: "+252", iso: "so" },
  { name: "Soudan", code: "+249", iso: "sd" },
  { name: "Soudan du Sud", code: "+211", iso: "ss" },
  { name: "Sri Lanka", code: "+94", iso: "lk" },
  { name: "Suède", code: "+46", iso: "se" },
  { name: "Suisse", code: "+41", iso: "ch" },
  { name: "Suriname", code: "+597", iso: "sr" },
  { name: "Syrie", code: "+963", iso: "sy" },
  { name: "Tadjikistan", code: "+992", iso: "tj" },
  { name: "Taïwan", code: "+886", iso: "tw" },
  { name: "Tanzanie", code: "+255", iso: "tz" },
  { name: "Tchad", code: "+235", iso: "td" },
  { name: "Tchéquie", code: "+420", iso: "cz" },
  { name: "Thaïlande", code: "+66", iso: "th" },
  { name: "Timor Oriental", code: "+670", iso: "tl" },
  { name: "Togo", code: "+228", iso: "tg" },
  { name: "Tonga", code: "+676", iso: "to" },
  { name: "Trinité-et-Tobago", code: "+1-868", iso: "tt" },
  { name: "Tunisie", code: "+216", iso: "tn" },
  { name: "Turkménistan", code: "+993", iso: "tm" },
  { name: "Turquie", code: "+90", iso: "tr" },
  { name: "Tuvalu", code: "+688", iso: "tv" },
  { name: "Ukraine", code: "+380", iso: "ua" },
  { name: "Uruguay", code: "+598", iso: "uy" },
  { name: "Vanuatu", code: "+678", iso: "vu" },
  { name: "Vatican", code: "+379", iso: "va" },
  { name: "Venezuela", code: "+58", iso: "ve" },
  { name: "Vietnam", code: "+84", iso: "vn" },
  { name: "Wallis-et-Futuna", code: "+681", iso: "wf" },
  { name: "Yémen", code: "+967", iso: "ye" },
  { name: "Zambie", code: "+260", iso: "zm" },
  { name: "Zimbabwe", code: "+263", iso: "zw" }
];
